Ajout de l'écran  : formulaire d'identification d'un déchet
Firelods/DecheTri pull request #21
Opened 2024-03-25 18:22 UTC by emmaallain

2024-03-25 22:10 UTC, Antoine-FdRg requested changes

2024-03-25 22:10 UTC, Antoine-FdRg commented on app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastereport/WasteDetailsReportFragment.java
ya plein de chose inutile coté java mais j'imagine que t'y as pas touché juste donc oklm

2024-03-25 22:10 UTC, Antoine-FdRg commented on app/src/main/res/layout/fragment_waste_details_report.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
pouruqoi ne pas avoir mis le Linearlayout à la racine plutot que le FrameLayout ?

2024-03-25 22:10 UTC, Antoine-FdRg commented on app/src/main/res/layout/fragment_waste_details_report.xml
> +    <LinearLayout
ça manque un peu de marge je trouve

2024-03-25 22:10 UTC, Antoine-FdRg commented on app/src/main/res/layout/fragment_waste_details_report.xml
> +                tools:ignore="MissingConstraints" />
utilise un Linearlayout si tu veux pas t'embêter avec les contraintes

2024-03-25 22:10 UTC, Antoine-FdRg commented on app/src/main/res/layout/fragment_waste_details_report.xml
> +                app:layout_constraintHorizontal_bias="0.42"
fait gaffe à pas laisser de bias, c'est des position en dur c'est pas très bien

2024-03-25 22:10 UTC, Antoine-FdRg commented on app/src/main/res/layout/fragment_waste_details_report.xml
> +            <Button
le texte de tes 2 boutons repart à la ligne, tu peux peut-être bloquer le retour à la ligne

2024-03-29 17:06 UTC, BaptisteLacroix requested changes

2024-04-06 12:04 UTC, Antoine-FdRg approved these changes

2024-04-07 13:58 UTC, merged