Ajout de l'écran: Actualité
Firelods/DecheTri pull request #22
Opened 2024-03-25 18:37 UTC by BaptisteLacroix

Closes #1

2024-03-26 14:05 UTC, Antoine-FdRg requested changes

2024-03-26 14:05 UTC, Antoine-FdRg commented on app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/FluxFragment.java
> +
faut mettre tout ça dans une classe à part (qui extends ArrayList) pour pouvoir remplacer par la liste récupérée auprès de l'API plus tard

2024-03-26 14:05 UTC, Antoine-FdRg commented on app/src/main/res/drawable/shape.xml
rename pour donner un nom explicite

2024-03-26 14:05 UTC, Antoine-FdRg commented on app/src/main/res/layout/fragment_flux.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
pq utiliser un FramLayout ?

2024-03-26 19:02 UTC, Firelods approved these changes

2024-03-30 21:53 UTC, Antoine-FdRg approved these changes

2024-04-01 15:08 UTC, merged