Ajout de l'écran de confirmation de suppression d'un message
Firelods/DecheTri pull request #42
Opened 2024-04-18 09:41 UTC by BaptisteLacroix

Closes #17 

https://github.com/Firelods/DecheTri/assets/61122159/5186a866-d21e-4d3d-8c0a-211dd592a9e3

![image](https://github.com/Firelods/DecheTri/assets/61122159/335d6a79-503b-4879-b5ed-42c57aa4d0c1)

2024-04-22 13:13 UTC, Antoine-FdRg reviewed
on pourrait peut etre ajouter des couleur surs les boutons de l'AlertDialog comme ici :
![image](https://github.com/Firelods/DecheTri/assets/104559304/4185c5f4-f4f8-4e16-85d1-cae817893543)

2024-04-22 17:36 UTC, BaptisteLacroix commented
> on pourrait peut etre ajouter des couleur surs les boutons de l'AlertDialog comme ici : ![image](https://private-user-images.githubusercontent.com/104559304/324472565-4185c5f4-f4f8-4e16-85d1-cae817893543.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDcxNDAsIm5iZiI6MTcxMzgwNjg0MCwicGF0aCI6Ii8xMDQ1NTkzMDQvMzI0NDcyNTY1LTQxODVjNWY0LWY0ZjgtNGUxNi04NWQxLWNhZTgxNzg5MzU0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxNzI3MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzZiYzUxNDAzYzg0ZTM1NjkzODNhMjliM2MwYTY2MTQxOTZhN2RhNmU4ZjBiYTRkOTBmZDg1Njc3ZDI0ZGZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Uots3dghl7avpkfrSmst87X0AOe3ihF_Vgz485f3-ds)

![image](https://github.com/Firelods/DecheTri/assets/61122159/20eed96c-1af8-447a-941d-71b9a228d323)

2024-04-23 14:26 UTC, Antoine-FdRg commented
> > on pourrait peut etre ajouter des couleur surs les boutons de l'AlertDialog comme ici : ![image](https://private-user-images.githubusercontent.com/104559304/324472565-4185c5f4-f4f8-4e16-85d1-cae817893543.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDcxNDAsIm5iZiI6MTcxMzgwNjg0MCwicGF0aCI6Ii8xMDQ1NTkzMDQvMzI0NDcyNTY1LTQxODVjNWY0LWY0ZjgtNGUxNi04NWQxLWNhZTgxNzg5MzU0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxNzI3MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzZiYzUxNDAzYzg0ZTM1NjkzODNhMjliM2MwYTY2MTQxOTZhN2RhNmU4ZjBiYTRkOTBmZDg1Njc3ZDI0ZGZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Uots3dghl7avpkfrSmst87X0AOe3ihF_Vgz485f3-ds)
> 
> ![image](https://private-user-images.githubusercontent.com/61122159/324555948-20eed96c-1af8-447a-941d-71b9a228d323.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4ODI1ODAsIm5iZiI6MTcxMzg4MjI4MCwicGF0aCI6Ii82MTEyMjE1OS8zMjQ1NTU5NDgtMjBlZWQ5NmMtMWFmOC00NDdhLTk0MWQtNzFiOWEyMjhkMzIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDE0MjQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ODY4YWU5Y2NmZTdmMjU4MzA5ZDdiYWYzOTI0Nzg1ODNmNGI3MmU4Y2FmYThlMDdkMjNlYmEzZmY0ZmVkNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0pmUvyXIfWnYmaWh5jZvVBc3H16KfYy2TymgCYcC4I8)

si on veut tryhard l'UX, il faudrait pas ecrire "Confirmer" mais "Supprimer" et pas "Annuler" mais "Conserver"

2024-04-29 14:39 UTC, Antoine-FdRg requested changes

2024-04-29 14:39 UTC, Antoine-FdRg commented on app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/FluxFragment.java
> +        Log.d(TAG, "onClickBin: " + item);
tu peux clean tout ce qui est commentaire et log

2024-04-29 14:39 UTC, Antoine-FdRg commented on app/src/main/res/values/strings.xml
> +    <string name="alert_delete_yes">Confirmer</string>
```suggestion
    <string name="alert_delete_yes">Supprimer</string>
```

2024-04-29 14:39 UTC, Antoine-FdRg commented on app/src/main/res/values/strings.xml
> +    <string name="alert_delete_no">Annuler</string>
```suggestion
    <string name="alert_delete_no">Conserver</string>
```

2024-05-09 12:50 UTC, BaptisteLacroix commented on app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/FluxFragment.java
> +        Log.d(TAG, "onClickBin: " + item);
ils sont supprimés dans l'autre pr

2024-05-10 07:28 UTC, Antoine-FdRg approved these changes

2024-05-10 11:20 UTC, merged