Adding the notification
Firelods/DecheTri pull request #75
Opened 2024-05-19 01:08 UTC by BaptisteLacroix

Closes #43

2024-05-28 09:16 UTC, Antoine-FdRg requested changes

2024-05-28 09:16 UTC, Antoine-FdRg commented on app/src/main/res/values/strings.xml
ajouter tous les messages envoyés dans les notifs dans le fichier strings

2024-05-28 13:49 UTC, Firelods requested changes

2024-05-28 13:49 UTC, Firelods commented on app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/FluxFragment.java
> +                                NotificationFactory.sendNotification(NotificationType.DELETE, getActivity(), getContext(), getString(R.string.delete_announcement), "Failed to delete announcement", No
text notif en français

2024-05-28 13:49 UTC, Firelods commented on app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/FluxFragment.java
> +                                NotificationFactory.sendNotification(NotificationType.DELETE, getActivity(), getContext(), getString(R.string.delete_announcement), "Announcement deleted successfully"
Text notif en français

2024-05-28 13:49 UTC, Firelods commented on app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/NewAnnouncementFragmentDialog.java
> +                    NotificationFactory.sendNotification(NotificationType.CREATE, getActivity(), getContext(), getString(R.string.create_announcement), "Failed to create announcement", NotificationHe
Text en fr

2024-05-28 13:49 UTC, Firelods commented on app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/NewAnnouncementFragmentDialog.java
> +                        NotificationFactory.sendNotification(NotificationType.CREATE, getActivity(), getContext(), getString(R.string.create_announcement), "Announcement created successfully", Notifi
Text en fr

2024-05-28 13:49 UTC, Firelods commented on app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/NewAnnouncementFragmentDialog.java
> +                            Toast.makeText(getContext(), R.string.add_announcement_result_error + " : " + body, Toast.LENGTH_SHORT).show();
text en Fr

2024-05-28 13:49 UTC, Firelods commented on app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastemap/WasteDialogFragment.java
> +                    NotificationFactory.sendNotification(NotificationType.TASK_COMPLETED, getActivity(), getContext(), String.valueOf(R.string.error_completing_task), "Error completing task for waste
Texte en fr

2024-05-28 13:49 UTC, Firelods commented on app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastemap/WasteDialogFragment.java
> +                            NotificationFactory.sendNotification(NotificationType.DELETE, getActivity(), getContext(), String.valueOf(R.string.error_deleting_task), "Error deleting waste : " + waste.
Text en fr

2024-05-28 13:49 UTC, Firelods commented on app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastemap/WasteDialogFragment.java
> +                                NotificationFactory.sendNotification(NotificationType.DELETE, getActivity(), getContext(), String.valueOf(R.string.error_deleting_task), "Error deleting waste : " + wa
Texte en fr

2024-05-30 20:45 UTC, BaptisteLacroix commented on app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/NewAnnouncementFragmentDialog.java
> +                            Toast.makeText(getContext(), R.string.add_announcement_result_error + " : " + body, Toast.LENGTH_SHORT).show();
m'enfou c'est des logs pas visible pour l'utilisateur

2024-06-01 13:44 UTC, Antoine-FdRg requested changes
c'est nice mais il reste plein de string qui sont pas dans strings.xml

2024-06-01 13:44 UTC, Antoine-FdRg commented on app/src/main/java/etu/seinksansdoozebank/dechetri/model/waste/WasteList.java
>                      Toast.makeText(context, "Erreur lors de la récupération des déchêts : " + message, Toast.LENGTH_SHORT).show();
clément à ajouter des strings avec paramètres pour afficher des Toast, lets use them

2024-06-01 13:44 UTC, Antoine-FdRg commented on app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/FluxFragment.java
> +            // swipeRefreshLayout.setPadding(0,0,0,160);
pense à supprimer

2024-06-01 13:44 UTC, Antoine-FdRg commented on app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/FluxFragment.java
> +                                NotificationFactory.sendNotification(NotificationType.DELETE, getActivity(), getContext(), getString(R.string.delete_announcement), "Erreur lors de la suppression de l
passe en string

2024-06-01 13:44 UTC, Antoine-FdRg commented on app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/FluxFragment.java
> +                                NotificationFactory.sendNotification(NotificationType.DELETE, getActivity(), getContext(), getString(R.string.delete_announcement), "Annonce supprimée avec succès", No
idem

2024-06-02 08:43 UTC, Antoine-FdRg approved these changes

2024-06-02 12:45 UTC, merged