Déplacement du bouton "+" d'ajout d'annonce dans la toollbar
Firelods/DecheTri pull request #79
Opened 2024-05-20 13:54 UTC by Antoine-FdRg

le bouton flottant gênait le clic sur les poubelles

2024-05-20 14:34 UTC, BaptisteLacroix commented
Give us a screen for pity's sake please

2024-05-20 14:39 UTC, BaptisteLacroix requested changes

2024-05-20 14:39 UTC, BaptisteLacroix commented on app/src/main/res/layout/fragment_flux.xml
> +    <!--        app:layout_anchor="@id/swipeRefreshLayout" />-->
Pourquoi garder en commentaire ?

2024-05-20 14:39 UTC, BaptisteLacroix commented on app/src/main/java/etu/seinksansdoozebank/dechetri/ui/flux/FluxFragment.java
> -        }
n'importe quel utilisateur peut faire une annonce si tu enlèves ca, il faut le mettre a l'endroit ou tu as mis le boutons ajouter une annonce

2024-05-21 12:07 UTC, BaptisteLacroix approved these changes

2024-05-21 12:20 UTC, emmaallain approved these changes

2024-05-21 13:32 UTC, merged