Amélioration de l'affichage de la date pour l'utilisateur
Firelods/DecheTri pull request #96
Opened 2024-05-23 17:22 UTC by BaptisteLacroix

Closes #76

2024-05-27 19:28 UTC, Antoine-FdRg requested changes

2024-05-27 19:28 UTC, Antoine-FdRg commented on app/src/main/res/layout/item_flux.xml
> +
ya une big marge sous la date des evenements. 
![image](https://github.com/Firelods/DecheTri/assets/104559304/857285e7-8bd2-4da8-acee-b8470d3292e1)
il faudrait déplacer la textView  de date d'event à gauche du calendrier et donc la cacher pour les annonces genre comme ça :
![image](https://github.com/Firelods/DecheTri/assets/104559304/aef3d100-467a-4a68-b380-a9ddf15eafdc)

2024-05-28 13:43 UTC, Firelods requested changes

2024-05-28 13:43 UTC, Firelods commented on app/src/main/java/etu/seinksansdoozebank/dechetri/ui/wastemap/WasteDialogFragment.java
> +                    requireActivity().runOnUiThread(() -> Toast.makeText(getContext(), "Failure completing task : " + e.getMessage(), Toast.LENGTH_SHORT).show());
Traduire ça

2024-05-28 18:49 UTC, Antoine-FdRg approved these changes

2024-05-30 20:32 UTC, merged